### ISSUE TITLE
Markdown preview

### ISSUE THREAD

**Issue by cookchen233** [DetachHead/rebased#186]
### Description

Are there any plans to include a Markdown preview? I barely use VS Code, now that I have Rebased, there's really no reason to stick with VS Code for project management.

**Comment by DetachHead** [comment]
i don't intend to add back any of the language-specific plugins, sorry (with the exception of the basic syntax highlighting provided by the textmate plugin).

rebased is only meant for git related operations. for language-specific features you should just use vscode or another IDE

**Comment by cookchen233** [comment]
Fine. So now I need to use four tools: VS Code (project files window), VS Code (prompt/spec files window), Rebased and Codex

**Comment by DetachHead** [comment]
not sure why you need two vscode instances? IMO most of the time when viewing files in rebased it should be for viewing diffs/resolving conflicts.

i agree that it's annoying having to use more than one tool, but unfortunately vscode's git integration sucks and intellij's language support sucks, which meant i had two IDEs open eating up memory so i made rebased as a way to mitigate that by stripping out everything that isn't covered by vscode.

your setup sounds quite foreign to me as i don't use any AI tools other than chatgpt. maybe look into the AI integrations in intellij to see if they work for you?

**Comment by muescha** [comment]
Since Markdown has become much more widely used because of AI, it would be interesting to reconsider it.

However, I agree that once Markdown support is added, more and more plugins may end up being included by default.

**Comment by cookchen233** [comment]
Yes, absolutely. We used to rely on VS Code for actual coding, but with AI now, our workflow has shifted. We mostly use it to manage and review code, or to read and edit specs and prompt documents. It's essentially become a tool for managing files, especially markdown files. As for why we don't use JetBrains tools are just far superior. So, could Rebased be a viable alternative to VS Code? After all, JetBrains tools are just incredibly good.

**Comment by muescha** [comment]
There is already a plugin for Markdown:

https://plugins.jetbrains.com/plugin/7793-markdown/

But I can not install it via the Market Place.

The search don't give me the Plugin: `/vendor:"JetBrains s.r.o." markdown`:

<img width="1544" height="926" alt="Image" src="https://github.com/user-attachments/assets/6f407eae-c92e-4c6b-8062-3ba99f7cd03d" />

Is there a way to get it into rebased?

**Comment by DetachHead** [comment]
i'll take a look

**Comment by muescha** [comment]
since the original [Markdown plugin from JetBrains](https://plugins.jetbrains.com/plugin/7793-markdown) was not in the Marketplace list (this plugin was only available for some standard JetBrains IDEs but not for rebased),

I now tried this third-party plugin:

https://plugins.jetbrains.com/plugin/17254-markdown-editor

Since JCEF was not enabled by default, I got it working with this guide:

https://joachimschuster.de/posts/android-studio-markdown-struggle-never-ends/

I selected this runtime: `25.0.3+9-329.124-jcef JetBrains Runtime`  
or the name from the dropdown list: `25.0.3 JetBrains Runtime JBR with JCEF (bundled by default)`

Don't forget to switch to the "Markdown Editor" tab at the bottom of the file.

Also note that the editor is not enabled in the diff view - only when the file itself is opened directly, not in the diff view (shortcut to jump to the file from the diff: `cmd + ↓`).

**Comment by DetachHead** [comment]
thanks for looking into this. unfortunately, if adding markdown preview means also adding back JCEF then it's certainly something i'm not going to add back to rebased i'm afraid. bundling an entire chromium instance into my git client goes against my goal of making a de-bloated jetbrains IDE. (it increases the build size by about 40%!)

**Comment by muescha** [comment]
Oh, is the official Markdown plugin from JetBrains also based on JCEF?

I understand your goal and agree with it. My workaround is mainly intended for those who urgently need rendered Markdown. :)

**Comment by muescha** [comment]
The confusion for me was that the TextMate plugin already shows a checkmark next to the Markdown bundle, so I assumed Markdown support was active. However, it only highlights `#` as a comment, while most other Markdown syntax is not visually highlighted.

**Comment by DetachHead** [comment]
yeah it seems that the builtin textmate bundle for markdown is pretty bad. i'll see if there's a better one we can use instead

**Comment by DetachHead** [comment]
> Oh, is the official Markdown plugin from JetBrains also based on JCEF?

sorry i misunderstood your comment, i thought that's what you were saying lol.

i was able to verify in #226 that the jetbrains markdown plugin does work without JCEF, though that doesn't really change my mind, i still don't think it makes sense to keep a plugin that's neither git-related nor is it useful when viewing diffs/conflicts. (though i agree it's unfortunate that some plugins are published to the plugin marketplace and others aren't)

since you guys have a workaround anyway, i think i'll close this. for transparency i'm also going to add some documentation to the readme explaining my thought process for these decisions

**Comment by DetachHead** [comment]
> since the original [Markdown plugin from JetBrains](https://plugins.jetbrains.com/plugin/7793-markdown) was not in the Marketplace list (this plugin was only available for some standard JetBrains IDEs but not for rebased),

it looks like the issue here is that the markdown extension wasn't being published to the marketplace at all since 2024. it seems like they've just recently started publishing it again, but for newer builds (presumably 2026.2 EAPs) which are not yet merged into rebased:

<img width="988" height="950" alt="Image" src="https://github.com/user-attachments/assets/c6b4074f-90e2-42f9-af71-90ed4fd97d31" />

if this is the case, the issue should fix itself when i merge 2026.2. regardless, i'll keep this issue open for now to remind myself to revisit this when 2026.2 is released.

**Comment by DetachHead** [comment]
https://youtrack.jetbrains.com/issue/IJPL-237337/Markdown-plugin-is-not-published-to-Marketplace

**Comment by wxyShine** [comment]
Hello！ Has 2026.2 been released? Can the Markdown plugin be used now?
<img width="426" height="435" alt="Image" src="https://github.com/user-attachments/assets/252d3ea8-ac85-4662-bb37-74d65cfe5ba9" />

**Comment by DetachHead** [comment]
i'll try to get it merged today and find out

**Comment by DetachHead** [comment]
confirmed that [the markdown plugin](https://plugins.jetbrains.com/plugin/7793-markdown) can now be installed from the marketplace in 2026.2, though i did have to make some changes on my end (see #288). i still need to push some more fixes to the 2026.2 branch before doing a release though

note that the markdown plugin now has an optional dependency on JCEF for rendering some elements in markdown files that contain HTML. luckily, [JCEF is now available as a plugin on the marketplace too](https://plugins.jetbrains.com/plugin/31360-web-browser-jcef-)

**Comment by muescha** [comment]
Maybe you misunderstood this Web Browser plugin 🤔 I understand that this plugin also need a JCEF Java version.

**Comment by DetachHead** [comment]
nope, here it is working with a JCEF-less build of rebased:

<img width="1022" height="514" alt="Image" src="https://github.com/user-attachments/assets/eeea2efd-bb14-4ebb-a42f-9da9c1a0492e" />

(edit: i just realized the JCEF plugin still adds the JCEF version to the about window so that screenshot doesn't prove much, but you can try it yourself)

looks like it works by [running jcef in a separate process](https://github.com/JetBrains/jcef#out-of-process-cef):

<img width="137" height="41" alt="Image" src="https://github.com/user-attachments/assets/984fe8ee-5e00-469b-a865-7952072d7f1a" />

**Comment by muescha** [comment]
Thanks for the feedback. Then I'm curious whether the new rebased version also works with the Markdown Editor plugin and the Web Browser plugin.

- https://plugins.jetbrains.com/plugin/17254-markdown-editor

**Comment by DetachHead** [comment]
looks like it doesn't. crashes on startup:

```
java.lang.NoClassDefFoundError: com/intellij/ui/jcef/JBCefApp
```

though it doesn't seem to work in IDEA 2026.2 either, so i'm assuming that plugin needs to be updated to work with the new JCEF implementation, so there's nothing i can do on my end i'm afraid

**Comment by DetachHead** [comment]
https://github.com/shuzijun/markdown-editor/issues/136#issuecomment-5008628522
